Caption_templates = [
            "Can you provide a caption consists of {} for this medical image?",
            "Describe the {} of the medical image you see.",
            "Please caption this medical scan with {}.",
            "What is the {} of this image?",
            "Describe this medical scan with {}.",
            "Please write a caption consists of {} for this image.",
            "Can you summarize with {} the images presented?",
            "Please caption this scan with {}.",
            "Please provide a caption consists of {} for this medical image.",
            "Can you provide a summary consists of {} of this radiograph?",
            "What are the {} presented in this medical scan?",
            "Please write a caption consists of {} for this scan.",
            "Can you provide a description consists of {} of this medical scan?",
            "Please caption this medical scan with {}.",
            "Can you provide a caption consists of {} for this medical scan?",
            # "Please generate a medical report based on this image.",
            # "Can you generate a diagnose report from this image.",
            "Could you analyze and provide a caption for the {} in this medical image?",
            # "Please describe the observations depicted in this medical scan.",
            "Can you summarize the {} of this image in a caption?",
            "What are the significant {} in this medical image?",
            "Please provide a detailed caption outlining the {} of this image.",
            "Could you interpret and describe the {} shown in this medical scan?",
            # "What conclusions can you draw from the observations in this image?",
            "Please write a descriptive caption based on the {} in this scan.",
            "What key {} can you identify from examining this medical image?",
            # "Could you generate a detailed report based on the observations in this image?",
            "Can you provide a diagnosis based on the {} in this image?",
            "Please generate a comprehensive report summarizing the {} in this image.",
            "Caption the {} in this medical image?",
            "Describe the {} you see.",
            "Caption this medical scan's {}.",
            "What are the {} here?",
            "Describe these {}.",
            "Summarize the {} in these images.",
            "Caption this scan's {}.",
            "Provide a caption for this medical image's {}.",
            "Summarize the {} of this radiograph.",
            "What {} are presented in this scan?",
            "Describe this scan's {}.",
            # "Generate a medical report based on this image.",
            # "Can you provide a diagnosis based on this image?",
]
Caption_templates_zh = [
            "你能为这张医学影像提供一个包含{}的描述吗？",
            "请描述你看到的医学影像的{}。",
            "请用{}为这张医学扫描配一个说明。",
            "这张图片的{}是什么？",
            "请用{}描述这张医学扫描。",
            "请为这张图片写一个包含{}的说明。",
            "你能用{}总结一下所展示的图片吗？",
            "请用{}为这张扫描配一个说明。",
            "请为这张医学影像提供一个包含{}的描述。",
            "你能为这张放射片提供一个包含{}的总结吗？",
            "在这张医学扫描中呈现的{}是什么？",
            "请为这张扫描写一个包含{}的说明。",
            "你能为这张医学扫描提供一个包含{}的描述吗？",
            "请用{}为这张医学扫描配一个说明。",
            "你能为这张医学扫描提供一个包含{}的说明吗？",
            # "请根据这张图片生成一份医学报告。",
            # "你能根据这张图片生成一份诊断报告吗？",
            "你可以分析并为这张医学影像中的{}提供一个说明吗？",
            # "请描述这张医学扫描中所展示的观察结果。",
            "你能用一个说明总结这张图片的{}吗？",
            "这张医学影像中有哪些重要的{}？",
            "请提供一份详细的说明，概述这张图片的{}。",
            "你可以解释并描述这张医学扫描中呈现的{}吗？",
            # "你能根据这张图片中的观察结果得出什么结论？",
            "请根据这张扫描中的{}写一个描述性说明。",
            "通过检查这张医学影像，你能识别出哪些关键的{}？",
            # "你能根据这张图片中的观察结果生成一份详细报告吗？",
            "你能根据这张图片中的{}提供一个诊断吗？",
            "请生成一份总结这张图片中{}的综合报告。",
            "为这张医学影像中的{}配一个说明？",
            "描述你看到的{}。",
            "为这张医学扫描的{}配一个说明。",
            "这里有哪些{}？",
            "描述这些{}。",
            "总结这些图片中的{}。",
            "为这张扫描的{}配一个说明。",
            "为这张医学影像的{}提供一个说明。",
            "总结这张放射片的{}。",
            "这张扫描中呈现了哪些{}？",
            "描述这张扫描的{}。",
            # "根据这张图片生成一份医学报告。",
            # "你能根据这张图片提供一个诊断吗？",
]

PosREC_templates = {
"cls_questions": [
    "Can you find the {} in this image? Give coordinates.",
    "Can you find {} in this image? Please output the coordinates.",
    "Please bounding the {} by box in this image.",
    "Where is {} in this image? Please respond with a bounding box.",
    "Where is {} in this image? Please output the box.",
    "Can you locate the {} in this image? Please output its coordinates.",
    "Could you mark the {} by bounding box in this image?",
    "Where can I find the {} in this image? Please provide its bounding box.",
    "Identify the indicated {} in this image. Please provide the coordinates of its bounding box.",
    "Can you locate the {} in this image? Please provide coordinates.",
    "Where is the {} in this image? Please output its coordinates.",
    "Please outline the {} with a bounding box in this image.",
    "Identify the location of {} in this image. Provide the bounding box coordinates.",
    "Where can I find the {} in this image? Please give its bounding box.",
    "Locate the {} in this image. Output its coordinates, please.",
    "Could you mark the {} with a bounding box in this image?",
    "Spot the {} in this image and provide its bounding box coordinates.",
    "Please pinpoint the {} in this image. Output its coordinates.",
    "Identify the {} indicated in this image. Provide coordinates for its bounding box.",
],

"des_questions": [
    "Description: {} Please answer and find it by box based on the above description.",
    "Definition: {} Please answer and show the bounding box based on the above definition.",
    "Description: {} Can you answer and find it by coordinates based on the above description.",
    "Definition: {} Please output the bounding box and answer based on the above definition.",
    "Description: {} Respond and locate it using a bounding box according to the description.",
    "Definition: {} Please provide an answer and display the bounding box according to the given definition.",
    "Description: {} Can you identify and locate it by coordinates, following the provided description or definition?",
    "Definition: {} Please output the bounding box and provide an answer based on the provided definition.",
    "Based on the description or definition, please respond to {} and indicate its location with a bounding box.",
    "{} Please answer and find it by box based on the above description.",
    "{} Please answer and show the bounding box based on the above definition.",
    "{} Can you answer and find it by coordinates based on the above description.",
    "{} Please output the bounding box and answer based on the above definition.",
    "{} Respond and locate it using a bounding box according to the description.",
    "{} Please provide an answer and display the bounding box according to the given definition.",
    "{} Can you identify and locate it by coordinates, following the provided description or definition?",
    "{} Please output the bounding box and provide an answer based on the provided definition.",
    "Please answer and find it by box based on the description. {}",
    "Please answer and show the bounding box based on the definition. {}",
    "Can you answer and find it by coordinates based on the description. {}",
    "Please output the bounding box and answer based on the definition. {}",
    "Respond and locate it using a bounding box according to the description. {}",
    "Please provide an answer and display the bounding box according to the given definition. {}",
    "Can you identify and locate it by coordinates, following the provided description or definition? {}",
    "Please output the bounding box and provide an answer based on the provided definition. {}",
    "Description: {} Find and mark it with a bounding box.",
    "Definition: {} Show the bounding box and provide the answer.",
    "Describe: {} Identify and locate it by coordinates.",
    "Define: {} Output the bounding box and respond.",
    "Description: {} Locate it with a bounding box.",
    "Definition: {} Provide the answer with the bounding box.",
    "Description: {} Identify and locate it by coordinates.",
    "Definition: {} Output the bounding box with the answer.",
    "{} Answer and locate with a bounding box.",
    "{} Show the bounding box based on the definition.",
    "{} Locate it by coordinates according to the description.",
    "{} Output the bounding box and answer.",
    "{} Respond and locate with a bounding box.",
    "{} Provide the answer with the bounding box.",
    "{} Identify and locate by coordinates.",
    "{} Output the bounding box with the answer.",
],

"cls_answers": [
    "Coordinates are {}.",
    "Sure, {}.",
    "Sure, it is {}.",
    "Sure, the bounding box is {}.",
    "{}.",
    "Here are the coordinates: {}.",
    "Of course, it's located at {}.",
    "The bounding box is given by {}.",
    "The box is {}.",
    "Coordinates: {}.",
    "{}.",
    "Yes, {}.",
    "{} are the coordinates.",
    "Sure, it's at {}.",
    "The bounding box: {}.",
    "{} - here are the coordinates.",
    "{} - it's located at these coordinates.",
    "The box: {}.",
    "Coordinates: {}.",
    "Certainly, it's at {}.",
    "Yes, it is located at {}.",
    "Sure, the bounding box: {}.",
    "It's located at {}.",
    "Here are the coordinates: {}.",
    "Of course, it's positioned at {}.",
    "The bounding box can be described by: {}.",
    "The box is specified by: {}.",
    "Yes, the coordinates are {}.",
    "Sure, it's located around {}.",
    "Yes, it's within the bounding box: {}.",
    "Absolutely, the coordinates: {}.",
    "Yes, it's within the box: {}.",
],

"des_answers": [
    "The target is {} and the coordinates is {}.",
    "The category is {} and the bounding box is {}.",
    "It is {}, {}.",
    "{}, {}",
    "The target is identified as {} and its coordinates are {}.",
    "The category is {}, the bounding box is provided as {}.",
    "It is characterized by {}, with coordinates {}.",
    "The identified attributes are {}, {}.",
    "Describing it as {}, the corresponding box is {}.",
    "The target is {} and its coordinates are {}.",
    "Categorized as {}, with a bounding box of {}.",
    "It's {}, located at {}.",
    "It's characterized as {}, with coordinates {}.",
    "Identified as {}, with a bounding box: {}.",
    "Belongs to the category of {}, with coordinates {}.",
    "Characterized by {}, with a bounding box given as {}.",
    "Describing it as {}, with coordinates {}.",
    "Identified attributes: {}, with a bounding box of {}.",
    "The category is {}, and the coordinates are {}.",
    "Describing it as {}, its bounding box is {}.",
    "It falls under the category of {}, with coordinates {}.",
],

"cls_no_answers": [
    "Sorry, there is no {}.",
    "No, we can not see {}.",
    "{} is not here.",
    "Sorry, there's no {} in sight.",
    "Unfortunately, {} is not visible here.",
    "No, {} is not present in this image.",
    "Apologies, but there's no sign of {}.",
    "We couldn't find {} in this image.",
    "It seems {} is not included in this image.",
    "Sorry, no {} found.",
    "No {} visible.",
    "Not seeing {} here.",
    "{} absent.",
    "No {} detected.",
    "Can't find {} in this image.",
],

"des_no_answers": [
    "This is {}, but not here.",
    "This is {}, however we can not see it.",
    "This is {}, but it's not present here.",
    "This is {}, but unfortunately, it's not visible in this context.",
    "While this is {}, it doesn't seem to be here.",
    "This is {}, but it's not depicted in this image.",
    "While this is {}, it's not currently observable in this scene.",
    "{} mentioned, but not here.",
    "{} described, but not visible.",
    "This is {}, but it's not here.",
    "This is {}, but it's not visible.",
    "{} mentioned, but not depicted here.",
    "{} described, but not present.",
]
}


PosREG_templates = {
"cls_questions": [
            "What target is present within the coordinates {} ?",
            "Does the bounding box {} contain any target?",
            "Within the specified region {}, what target is present?",
            "Do you know what it is in the bounding box {}?",
            "What is it in this region {}?",
            "What object is located within the coordinates {}?",
            "Within the specified area {}, what object can be found?",
            "Can you identify the object within the bounding box {}?",
            "What object is present in this region {}?",
            "What's within coordinates {}?",
            "Does the box {} contain any target?",
            "What's in the region {}?",
            "What's within the box {}?",
            "What object is in this region {}?",
            "What's located within coordinates {}?",
            "What's within the area {}?",
            "Can you identify the object within box {}?",
            "What object is present in this area {}?",
            "What target can be found within coordinates {}?",
            "Is there any target within the bounding box {}?",
            "Within the specified region {}, what target is present?",
            "Can you identify what's within the bounding box {}?",
            "What object is present in this region {}?",
            "What's located within coordinates {}?",
            "Within the specified area {}, what object can be found?",
            "Could you identify the object within the bounding box {}?",
            "What object is present in this region {}?",
            "What's located at coordinates {}?",
            "Is there a target within the box {}?",
            "What's situated in the region {}?",
            "What's inside the box {}?",
            "What object can be found in this region {}?",
            "What's situated within coordinates {}?",
            "What's within the specified area {}?",
            "Can you identify any object within box {}?",
            "What object is present in this area {}?",
        ],

"des_questions": [
            "Please describe the target and its function based on the box {} in the image.",
            "Do you know what is it in this bounding box {}? Answer and explain it.",
            "What's the target in the bounding box {}? What function does it have?",
            "What is the area marked with a box {} in the image? Can you explain it?",
            "Could you describe the object and its purpose within the bounding box {} in the image?",
            "Can you identify and describe the object within this bounding box {}? Please explain.",
            "What is the object located in the bounding box {}? Could you explain its function?",
            "Could you describe the area outlined by the box {} in the image? Please explain its significance.",
            "Describe the target and its function in box {}.",
            "What's in this box {}? Describe and explain.",
            "What's in the box {}? Explain its function.",
            "What's inside the box {}? Can you describe it?",
            "Describe the object in box {} and its purpose.",
            "Identify and describe the object in box {}. Please explain.",
            "What's the object in box {}? Describe its function.",
            "Describe the area outlined by box {} and its significance.",
            "What's in the marked area {}? Please explain.",
        ],

"cls_answers": [
            "The target is {}.",
            "Sure, the bounding box contains {}.",
            "Sure, it is {}.",
            "Sure, {} is in the bounding box.",
            "{}.",
            "The object is {}.",
            "Of course, it's {}.",
            "Certainly, {} can be found in the bounding box.",
            "Yes, the bounding box includes {}.",
            "The target is identified as {}.",
            "Affirmative, the bounding box contains {}.",
            "Yes, it is indeed {}.",
            "Yes, {} is within the bounding box.",
            "The object in question is {}.",
            "Of course, it's indeed {}.",
            "Certainly, {} can be found within the bounding box.",
            "Yes, the bounding box includes {}.",
            "Indeed, {} is present within the bounding box.",
            "Confirmed, the object is {}.",
            "Absolutely, it's {}.",
        ],

"des_answers": [
            "Sure, it is {}. {}",
            "The category is {}. {}",
            "It is {}, {}",
            "{}, {}",
            "The target is identified as {} and its description is {}",
            "The category is {}. Description: {}",
            "It is characterized by {}, {}",
            "The identified attributes are {}, {}",
            "Sure, it is {}. Describing it as {}",
            "Certainly, it is {}. {}",
            "The category is identified as {}. {}",
            "It's labeled as {}, {}",
            "Identified as {}, {}",
            "The target is recognized as {} with the following description: {}",
            "The category is {}. Here's the description: {}",
            "Characterized by {}, {}",
            "Identified attributes: {}, {}",
            "Sure, it's {}. Described as {}",
        ],

"cls_no_answers": [
    "Sorry, there is no {}.",
    "No, we can not see {}.",
    "{} is not here.",
    "Sorry, we couldn't find any {}.",
    "Nope, {} isn't visible here.",
    "{} seems to be absent.",
    "Unfortunately, {} is not present.",
    "It appears there's no {} in sight.",
    "Regrettably, we couldn't detect any {}.",
],

"des_no_answers": [
    "This is {}, but not here.",
    "This is {}, however we can not see it.",
    "This is {}, but it's not present here.",
    "This is {}, however, it's not visible in this context.",
    "The answer is {}, but it is not here.",
    "The object is {}, but it is absent in the image.",
]
}


Seg_templates = {
"cls_questions": [
            "Can you segment the {} in this image?",
            "Can you segment {} in this image? Please output the mask.",
            "Please segment the {} in this image.",
            "What is {} in this image? Please respond with segmentation mask.",
            "What is {} in this image? Please output segmentation mask.",
            "Could you provide a segmentation for the {}?",
            "I need the {} segmented from this image.",
            "Segment {} from this image and provide the mask, please.",
            "Please provide a segmentation mask for the {} in this image.",
            "Can you identify and segment the {} in this image?",
            "Could you segment the {} here and share the mask?",
            "I'm looking for segmentation of {} in this image.",
            "Can you segment the object labeled as {}?",
            "Segment the {} in this image, please.",
            "Please segment {} in this image and provide the mask.",
            "What's the segmentation for {} in this image?",
            "Segment the {} in this image and share the mask.",
            "Please provide segmentation for {} in this image.",
            "Could you segment the {} here and share the mask?",
            "Segment the object labeled as {} and provide the mask.",
            "I need the {} segmented from this image. Can you help?",
            "Can you identify and segment the {} in this image?",
            "Can you segment {} here and output the mask?",
            "Please segment the {} in this image and share the mask.",
            "Segment {} from this image and provide the mask, please.",
            "Can you segment the {} in this image?",
        ],

"des_questions": [
            "{} Please answer and segment.",
            "{} Please output segmentation mask and answer.",
            "{} Please answer and segment based on the above description.",
            "{} Please answer and segment based on the above definition.",
            "{} Can you answer and segment it based on the above description or definition.",
            "{} Please output segmentation mask and answer based on the above description or definition.",
            "{} Please segment accordingly.",
            "{} Please provide segmentation and answer according to it.",
            "{} Now, segment it and provide your answer.",
            "{} Please segment and provide your response.",
            "{} Can you segment it accordingly?",
            "Description: {} Please answer and segment based on the above description.",
            "Definition: {} Please answer and segment based on the above definition.",
            "Description: {} Can you answer and segment it based on the above description or definition.",
            "Definition: {} Please output segmentation mask and answer based on the above description or definition.",
            "Provided description: {} Please segment accordingly.",
            "Given definition: {} Please provide segmentation and answer according to it.",
            "The description provided is: {} Now, segment it and provide your answer.",
            "Based on the provided definition: {} Please segment and provide your response.",
            "Describing the object as: {} Can you segment it accordingly?",
            "Defining it as: {} Now, segment and provide your answer.",
        ],

"cls_answers": [
            "It is [SEG].",
            "Sure, [SEG].",
            "Sure, it is [SEG].",
            "Sure, the segmentation result is [SEG].",
            "[SEG].",
            "The segmentation indicates [SEG].",
            "According to the segmentation, it is [SEG].",
            "The segmentation reveals [SEG].",
            "The segmentation suggests [SEG].",
            "From the segmentation, it appears to be [SEG].",
            "The target is [SEG].",
            "The segmentation mask is [SEG].",
            "The mask is [SEG].",
],

"des_answers": [
            "The target is {} and the segmentation mask is [SEG].",
            "The category is {} and the mask is [SEG].",
            "It is {}, [SEG].",
            "{}, [SEG]",
            "Identified as {}, here is the segmentation: [SEG].",
            "Categorized as {}, the segmentation is: [SEG].",
            "The class is {}, and the corresponding segmentation is: [SEG].",
            "Regarding the classification, it is {}, and the segmentation is: [SEG].",
            "Classified as {}, here's the segmentation: [SEG].",
            "The label assigned is {}, and the associated segmentation is: [SEG].",
            "Category: {}, segmentation: [SEG].",
            "It's classified as {}, with the segmentation: [SEG].",
        ],

"cls_no_answers": [
            "Sorry, there is no {}.",
            "No, we cannot see {}.",
            "{} is not present.",
            "There's no sign of {} in this image.",
            "Unfortunately, {} is not visible in this image.",
            "We cannot detect {} in this image.",
            "There's no indication of {} here.",
            "Regrettably, {} cannot be observed in this image.",
            "Sorry, {} isn't here.",
            "{} is absent.",
            "Nope, {} is missing.",
            "We're not seeing any {}.",
        ],

"des_no_answers": [
    "This is {}, but not here.",
    "This is {}, however we can not see it.",
    "While this is {}, it's not within view.",
    "This appears to be {}, but it's not in this vicinity.",
    "Although this is {}, it's not visible here.",
    "Though this is {}, it's not captured in this scene.",
    "This is indeed {}, but it's not here in the image.",
    "While we've identified {}, it's not within this image.",
    "This seems to be {}, but it's not depicted here.",
    "While this describes {}, it's not shown in this image.",
]
}

rewrite_prompt = 'You are a professional CT medical report expert, \
            Please help me rewrite the following CT report. \
            The description is accurate and smooth when the rewriting means unchanged. \
            Here are some examples: \
            1. The liver is normal in size and shape with regular surface. The liver parenchyma density is uniform, and the common bile duct and intrahepatic bile duct are not dilated. The spleen is normal in size and shape with no abnormal density in the parenchyma. The position, shape, and density of the pancreas are normal, with no dilation of the pancreatic duct. The gallbladder is not enlarged, and the wall is not thickened. Both kidneys are normal in size and shape, while multiple cystic low-density lesions are observed with no obvious enhancement. No obvious enlarged lymph nodes are seen in the posterior peritoneum. No obvious abnormal enhancing foci is seen in the upper and lower abdomen.\
            2. A nodular high-density focus is seen in the right lobe of the liver, and no abnormal density is found in the remaining liver parenchyma. The intrahepatic duct system is not obviously dilated. The gallbladder is not enlarged with uniform density enhancement inside, while a focal high-density shadow is seen near the neck of the gallbladder. The surface of the pancreas is rough, with still uniform density and clear adjacent fat intervals. The spleen is enlarged. Multiple enlarged lymph nodes are found in the abdominal cavity and retroperitoneum.\
            3. Bilateral chest are symmetrical. A few patchy high-density shadows with blurred edges are observed in the right lung upper lobe and both lung lower lobes, and a few consolidations are visible in the right lung lower lobe. No narrowing or obstruction of the trachea and bronchus can be seen. Esophageal dilation is observed with mixed low-density shadows inside. No obvious enlarged lymph nodes is seen in the mediastinum or bilateral pulmonary hila. No significant abnormalities are observed in the heart or major blood vessels. No abnormal enhanced lesions are observed in the enhanced scan.\
            4. The chest is symmetrical, the lung window shows clear lung texture with natural course. A few cord-like high-density foci are seen in the middle and lower lobe of right lung, while no abnormal solid foci is seen in the remaining lungs. The bilateral pulmonary hila are normal. The trachea and bronchi are unobstructed. The mediastinal window shows no deviation of the mediastinum, and the morphology of the heart and major blood vessels are normal. No mass or enlarged lymph nodes is seen in the mediastinum. No pleural effusion or pleural thickening is seen on either sides.\
            5. The bladder is well-filled, and the bladder wall is smooth. No abnormal density foci is observed in the bladder wall or inside the bladder. The position, contour, and size of the prostate are normal, with scattered high-density foci inside. The bilaterally symmetrical seminal vesicles show no abnormal density. The surrounding fat space is clear. No abnormal enhancement is observed in other regions.\
            6. The prostate volume is not large, with a smooth contour and high-density points in local areas. The angle between the bladder and seminal vesicle is clear, and no obvious focal thickening or nodular foci are seen on the bladder wall. High-density foci are seen in the pelvis.\
            \
            Please fix the findings and impression into one sentence.\
            Please directly output the rewritten sentence in English. {}'